### PR TITLE
Cache & HTTP Client DI

### PR DESCRIPTION
**Pull request by Dwarfex**
This PR adds support for 

- Injecting an own httpClient
     - with independent config, thus allowing to set a custom header as asked for in #11 (this may be 
       "enforced" in the constructor in future?)
- Injecting PSR-16 Cache Interface (for those wanting to use PSR-6: there are several libraries to make 
   them interchangable. would suggest closing #12 
- additonal tests 
- overall improvements of Code Style and fixing some typos
- raised version number to 0.2.1 accordingly to semantic versioning (semver.org) via tag as this is new functionality

### CODE REVIEW

**Comment by rampmaster** [comment]
Looking this @Dwarfex

**Comment by rampmaster** [comment]
@Dwarfex is possible add testing for 7.1 and 7.3? thanks

**Comment by Dwarfex** [comment]
@rampmaster what exactly do you mean with "add testing"?
The current code does contain testing for 7.1. 
As the composer package states explicitly a PHP 7.1 (and up) requirement, code written in the library must only contain PHP 7.1 code in the current version.

**Comment by Dwarfex** [comment]
@rampmaster Thanks for merging. I noticed, that the Merge did not contain the version tags. It seems this has to be made manually for each repository.

I would suggest raising the version number to something like 0.2.0

**Pull request merged**
