### PR TITLE
Support for Guzzle 7.x

### PR DESCRIPTION
**Pull request by epalmans**
Allow either Guzzle 6 or 7.

TODO check/test compatibility among these versions

### CODE REVIEW

**Comment by Dwarfex** [comment]
It seems as if the API response has changed and leads the testing to fail.  #27 - has to be fixed before this PR can be merged.

**Comment by epalmans** [comment]
kinda had my fingers crossed that just a version bump for the guzzle dependency would work out well. Bit too optimistic I guess 😅

**Comment by Dwarfex** [comment]
yeah - i agree with you, i' with you that should've worked - it's a bit odd, that the API changed

**Comment by Dwarfex** [comment]
Closing this, as this is included and will be fixed with PR #28

**Pull request closed without merging**
