### PR TITLE
feat: add support for psr/log ^2.0

### PR DESCRIPTION
**Pull request by khalyomede**
### What

Adds support for psr/log ^2.0 (which blocks a pull request, see Part of section).

### Part of 

- https://github.com/openfoodfacts/openfoodfacts-laravel/issues/39

### CODE REVIEW

**Review by Dwarfex — APPROVED** [review]

**Comment by Dwarfex** [comment]
I 'll combine this with a new Version and update PHP too - sry for beeing late to the party

**Comment by Dwarfex** [comment]
see #47 - Code Style fixes there are still needed

**Review by Benoit382 — APPROVED** [review]

**Comment by khalyomede** [comment]
Well, I see 0.3.x-dev already contains expected changes (even better because `psr/log` is at `^3.0`). I will close this pull request and my issue will be solved when 0.3.0 is published. Sorry for the time loss...

**Comment by Dwarfex** [comment]
Absolutely no reason to be sorry! - Thx for pushing for improvement :)

**Pull request closed without merging**
